/*!
 * /**
 * * @file server-rspack.js
 * * @description Bundled output generated by Rspack
 * * --------------------------------------------------------------------------
 * * ⚡ Rspack Server App (Development)
 * * --------------------------------------------------------------------------
 * * • [   server-entry.js ] ──▶ [■ server-rspack.js ] ──▶ [   server-meteor.js ]
 * *
 * * This file is the bundled output generated by Rspack.
 * * It contains all application code and assets combined into one build.
 * * It is not used directly, but will be imported by the Meteor main module
 * * file (`server-meteor.js`) so that Meteor runs the Rspack bundle.
 * *
 * * ⚠️ Note: This file is autogenerated. It is not meant to be modified manually.
 * * These files also act as a cache: they can be safely removed and will be
 * * regenerated on the next build. They should be ignored in IDE suggestions
 * * and version control.
 * * /
 *
 * /* Code generated * /
 *
 */
(() => {
"use strict";
var __webpack_modules__ = ({
"./imports/api/links.js"(__unused_rspack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.d(__webpack_exports__, {
  LinksCollection: () => (LinksCollection)
});
/* import */ var meteor_mongo__rspack_import_0 = __webpack_require__("meteor/mongo");
/* import */ var meteor_mongo__rspack_import_0_default = /*#__PURE__*/__webpack_require__.n(meteor_mongo__rspack_import_0);

const LinksCollection = new meteor_mongo__rspack_import_0.Mongo.Collection('links');


},
"./server/main.js"(__unused_rspack_module, __unused_rspack___webpack_exports__, __webpack_require__) {
/* import */ var meteor_meteor__rspack_import_0 = __webpack_require__("meteor/meteor");
/* import */ var meteor_meteor__rspack_import_0_default = /*#__PURE__*/__webpack_require__.n(meteor_meteor__rspack_import_0);
/* import */ var _imports_api_links_js__rspack_import_1 = __webpack_require__("./imports/api/links.js");
/* import */ var meteor_random__rspack_import_2 = __webpack_require__("meteor/random");
/* import */ var meteor_random__rspack_import_2_default = /*#__PURE__*/__webpack_require__.n(meteor_random__rspack_import_2);
function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) {
    try {
        var info = gen[key](arg);
        var value = info.value;
    } catch (error) {
        reject(error);
        return;
    }
    if (info.done) {
        resolve(value);
    } else {
        Promise.resolve(value).then(_next, _throw);
    }
}
function _async_to_generator(fn) {
    return function() {
        var self = this, args = arguments;
        return new Promise(function(resolve, reject) {
            var gen = fn.apply(self, args);
            function _next(value) {
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value);
            }
            function _throw(err) {
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err);
            }
            _next(undefined);
        });
    };
}



function insertLink(_0) {
    return _async_to_generator(function*({ title, url }) {
        yield _imports_api_links_js__rspack_import_1.LinksCollection.insertAsync({
            title,
            url,
            createdAt: new Date()
        });
    }).apply(this, arguments);
}
meteor_meteor__rspack_import_0.Meteor.startup(()=>_async_to_generator(function*() {
        // If the Links collection is empty, add some data.
        if ((yield _imports_api_links_js__rspack_import_1.LinksCollection.find().countAsync()) === 0) {
            yield insertLink({
                title: "Do the Tutorial",
                url: "https://docs.meteor.com/tutorials/react/"
            });
            yield insertLink({
                title: "Follow the Guide",
                url: "https://docs.meteor.com/tutorials/application-structure/"
            });
            yield insertLink({
                title: "Read the Docs",
                url: "https://docs.meteor.com"
            });
            yield insertLink({
                title: "Discussions",
                url: "https://forums.meteor.com"
            });
            yield insertLink({
                title: "Join us on Discord",
                url: "https://discord.gg/6mS3wHNg"
            });
            yield insertLink({
                title: "Deploying in Galaxy",
                url: "https://www.meteor.com/hosting"
            });
        }
        // We publish the entire Links collection to all clients.
        // In order to be fetched in real-time to the clients
        meteor_meteor__rspack_import_0.Meteor.publish("links", function() {
            return _imports_api_links_js__rspack_import_1.LinksCollection.find();
        });
    })());
meteor_meteor__rspack_import_0.Meteor.methods({
    about () {
        return `This is a Meteor application running React with React Router. this is a generated id: ${meteor_random__rspack_import_2.Random.id()}`;
    }
});


},
"meteor/meteor"(module) {
module.exports = require("meteor/meteor");

},
"meteor/mongo"(module) {
module.exports = require("meteor/mongo");

},
"meteor/random"(module) {
module.exports = require("meteor/random");

},

});
// The module cache
var __webpack_module_cache__ = {};

// The require function
function __webpack_require__(moduleId) {

// Check if module is in cache
var cachedModule = __webpack_module_cache__[moduleId];
if (cachedModule !== undefined) {
return cachedModule.exports;
}
// Create a new module (and put it into the cache)
var module = (__webpack_module_cache__[moduleId] = {
exports: {}
});
// Execute the module function
__webpack_modules__[moduleId](module, module.exports, __webpack_require__);

// Return the exports of the module
return module.exports;

}

// webpack/runtime/compat_get_default_export
(() => {
// getDefaultExport function for compatibility with non-ESM modules
__webpack_require__.n = (module) => {
	var getter = module && module.__esModule ?
		() => (module['default']) :
		() => (module);
	__webpack_require__.d(getter, { a: getter });
	return getter;
};

})();
// webpack/runtime/define_property_getters
(() => {
__webpack_require__.d = (exports, definition) => {
	for(var key in definition) {
        if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
            Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
        }
    }
};
})();
// webpack/runtime/has_own_property
(() => {
__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
})();
// webpack/runtime/make_namespace_object
(() => {
// define __esModule on exports
__webpack_require__.r = (exports) => {
	if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
		Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
	}
	Object.defineProperty(exports, '__esModule', { value: true });
};
})();
var __webpack_exports__ = {};
// This entry needs to be wrapped in an IIFE because it needs to be isolated against other modules in the chunk.
(() => {
__webpack_require__.r(__webpack_exports__);
/* import */ var _server_main_js__rspack_import_0 = __webpack_require__("./server/main.js");
/**
* @file server-entry.js
* @description Entry point for Rspack build process
* --------------------------------------------------------------------------
* 🔌 Rspack Server Entry (Development)
* --------------------------------------------------------------------------
* • [■ server-entry.js ] ──▶ [   server-rspack.js ] ──▶ [   server-meteor.js ]
*
* This file is the entry point that Rspack uses to start the build process.
* It imports the module defined in `meteor.mainModule.server` inside package.json.
* From here, Rspack can trace the entire dependency graph of your application
* and generate the bundled output (`server-rspack.js`).
*
* ⚠️ Note: This file is autogenerated. It is not meant to be modified manually.
* These files also act as a cache: they can be safely removed and will be
* regenerated on the next build. They should be ignored in IDE suggestions
* and version control.
*/ /* Link to 🔌 Meteor Server Entry */ 

})();

module.exports = __webpack_exports__;
})()
;
//# sourceMappingURL=server-rspack.js.map