name: Build and push Docker Image

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-southeast-2
  ECR_REPOSITORY: kimply
  TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::827152325060:role/GitHubActionsECRPush
          aws-region: ${{ env.AWS_REGION }}
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:$TAG ./app

      - name: Tag and Push Docker Image
        run: |
          docker tag $ECR_REPOSITORY:$TAG \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$TAG
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$TAG

      - name: Pull and Build Docker Image
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --region ap-southeast-2 \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters "commands=[
              'cd /opt/kimply',
              'aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin $ECR_REGISTRY',
              'export APP_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$TAG',
              'docker pull $APP_IMAGE',
              'docker compose -f docker-compose.prod.yml --env-file .env config -q'
              'docker compose -f docker-compose.prod.yml --env-file .env up -d --no-deps app'
            ]" \
            --query "Command.CommandId" \
            --output text)

          echo "SSM command: $COMMAND_ID"

          aws ssm wait command-executed \
            --region ap-southeast-2 \
            --command-id "$COMMAND_ID" \
            --instance-id "$INSTANCE_ID" || true

          aws ssm get-command-invocation \
            --region "$AWS_REGION" \
            --command-id "$COMMAND_ID" \
            --instance-id "$INSTANCE_ID"
